### ISSUE TITLE
Отправка комбинаций клавиш

### ISSUE THREAD

**Issue by navoznov** [GyverLibs/EasyHID#1]
Напрмер, `CTRL+C `или `SHIFT+F11`.

**Comment by EdgarkoN** [comment]
Сейчас тоже сидел мучался, никак не получется, 

В данном случае нажимается только С 
Keyboard.press(KEY_LEFT_CONTROL);
Keyboard.press(KEY_C);

Тут толи не срабатывает толи тоже только С (непомню)
Keyboard.press(KEY_MOD_LEFT_CONTROL);
Keyboard.press(KEY_C);

Так тоже не получается. 
Keyboard.press(KEY_MOD_LEFT_CONTROL, KEY_C)

пробовал много вариантов и комбинаций, но ничего не сработало.

**Comment by GyverLibs** [comment]
Автор либы говорит, что ограничения на комбинации тянутся из либы VUSB, и тут видимо не получится починить

**Comment by GyverLibs** [comment]
пофиксили в 2.0
