### ISSUE TITLE
Ctrl+Alt+Tab = Переход в гибернацию

### ISSUE THREAD

**Issue by TRRAXT** [GyverLibs/EasyHID#14]
При нажатии на энкодер и прокрутке должно срабатывать нажатие Alt+Tab, но почему-то происходит отправка девайса в гибернацию(комп/ноут, на Android просто блокировка). Может я делаю что-то не так?

void loop() {
  if (enc.tick()) {
    if (enc.isClick())  Keyboard.clickMultimediaKey(KEY_PLAYPAUSE);           // Клик по кнопке
    else if (enc.isLeft())  Keyboard.clickMultimediaKey(KEY_VOL_UP);          // Вращение вправо
    else if (enc.isRight())   Keyboard.clickMultimediaKey(KEY_VOL_DOWN);      // Вращение влево
    else if (enc.isLeftH()){                                                  // Вращение вправо с нажатием
      Keyboard.clickSystemKey(KEY_LEFT_ALT);
      Keyboard.click(KEY_TAB);
    }
    else if (enc.isRightH()){                                                 // Вращение влево с нажатием
      Keyboard.clickSystemKey(KEY_LEFT_ALT);
      Keyboard.clickSystemKey(KEY_LEFT_SHIFT);
      Keyboard.click(KEY_TAB);
    }
  }

ATTiny88(MH-Tiny), не знаю какая версия библиотеки(скачал с пункта "Установка"), Arduino IDE 1.8.19, стандартные примеры работают хорошо.

UPD: А так же, возможно добавление скролла мыши?

**Comment by GyverLibs** [comment]
привет, исправил документацию, системные клавиши это только клавиши для сна и выключения. Все остальные обрабатываются через клик

**Comment by TRRAXT** [comment]
т.е никакого аль+таба?
