### ISSUE TITLE
Can you add another example picture in English? I can't understand Russian and can't translate

### ISSUE THREAD

**Issue by loerss** [GyverLibs/EasyHID#15]
Вы можете добавить еще один пример на английском языке, я не понимаю русский язык, не может быть переведен

**Comment by GyverLibs** [comment]
You need wiring diagram from readme, but in English?

**Comment by loerss** [comment]
yes

**Comment by GyverLibs** [comment]
https://github.com/GyverLibs/EasyHID/blob/main/docs/schemes_en.png

**Comment by kkouznet** [comment]
> https://github.com/GyverLibs/EasyHID/blob/main/docs/schemes_en.png

404 - page not found
