### ISSUE TITLE
Не определяется

### ISSUE THREAD

**Issue by maxim221** [GyverLibs/EasyHID#18]
Версия библиотеки v2.5, используется мега 328p (arduino old bootloader), версия arduino IDE 1.8.19, использую встроенный пример Mouse с soft detach (без soft detach тоже не работает), загружал пример Mouse - ожидал что будет двигаться мышь - по факту вообще ничего не происходит. 

Ни в винде, ни в линуксе никакой реакции.

**Comment by Nich1con** [comment]
> Версия библиотеки v2.5, используется мега 328p (arduino old bootloader), версия arduino IDE 1.8.19, использую встроенный пример Mouse с soft detach (без soft detach тоже не работает), загружал пример Mouse - ожидал что будет двигаться мышь - по факту вообще ничего не происходит.
> 
> Ни в винде, ни в линуксе никакой реакции.

Кварц 16 мгц? Кабель USB какой длины?
