### ISSUE TITLE
Serial port?

### ISSUE THREAD

**Issue by kbln** [GyverLibs/EasyHID#2]
Реально добавить поддержку Сериал порта, чтобы с той же Нанкой можно было без свистков общаться?

**Comment by Nich1con** [comment]
Переделав USB дескриптор, добавив отдельно еще два end-point и дописав свой класс сериала. Реально, открывай примеры для V-USB, но в этой либе этот функционал не планируется.

**Comment by Nich1con** [comment]
> Реально добавить поддержку Сериал порта, чтобы с той же Нанкой можно было без свистков общаться?

Переделав USB дескриптор, добавив отдельно еще два end-point и дописав свой класс сериала. Реально, открывай примеры для V-USB, но в этой либе этот функционал не планируется.
