### ISSUE TITLE
Вставка текста на русском языке

### ISSUE THREAD

**Issue by kraa965** [GyverLibs/EasyHID#22]
Привет, подскажите, как можно реализовать вставку русского текста, в видео выводился английский?

**Comment by GyverLibs** [comment]
Alt+Shift?

**Comment by kraa965** [comment]
я имею ввиду через print("Привет"), вместо привет, он выдает символы и другие буквы

**Comment by GyverLibs** [comment]
Ну он и не должен выдавать русские, это ведь клавиатура. Нужно переключить язык и писать английскими, которые соответствуют русским

**Comment by kraa965** [comment]
> Ну он и не должен выдавать русские, это ведь клавиатура. Нужно переключить язык и писать английскими, которые соответствуют русским

Получается, надо написать print("Ghbdtn"), переключить клаву и будет все по-русски. 
А если надо передать текст из веб, ввожу в поле русский текст, а выдаются просто символы, как бы в таком случае?

**Comment by GyverLibs** [comment]
Надо писать свой парсер, который будет вытаскивать русские буквы из текста, переводить их в англ согласно qwerty раскладке, формировать строку и отправлять в принт. А если текст смешанный русско-англ - переключать язык, выдерживать паузу, но опять же обратной связи по языку нет, можно сбиться

**Comment by GyverLibs** [comment]
Можно посмотреть как парсит библиотека gyveroled, там все русские буквы обрабатываются

**Comment by kraa965** [comment]
> Можно посмотреть как парсит библиотека gyveroled, там все русские буквы обрабатываются

Есть же еще библиотека GParser, она может помочь?

**Comment by kraa965** [comment]
> Gparser разбивает текст на куски по заданному символу-разделителю

Видимо долблюсь в глаза, не нашел в gyveroled парсер, подскажите где она?

**Comment by GyverLibs** [comment]
Со строки 275 по 285
https://github.com/GyverLibs/GyverOLED/blob/main/src/GyverOLED.h

И дальше внизу функция getFont разбирает в таблицу

**Comment by GyverLibs** [comment]
Я могу закодить, но через несколько дней

**Comment by kraa965** [comment]
> Я могу закодить, но через несколько дней

буду очень сильно признателен

**Comment by GyverLibs** [comment]
Вот так можно преобразовать русскую строку в QWERTY
```cpp
const char _qwerty_ru[] PROGMEM = "F<DULT:PBQRKVYJGHCNEA{WXIO}SM\">Zf,dult;pbqrkvyjghcnea[wxio]sm'.z~`";

String ru_to_qw(const String& ru) {
  String qw;
  uint8_t prev = 0;
  for (int i = 0; i < ru.length(); i++) {
    uint8_t cur = ru[i];
    if (cur > 127) {
      uint8_t thiscur = cur;
      if (cur > 191) cur = 0;
      else if (prev == 209 && cur == 145) cur = 193;   // ё
      else if (prev == 208 && cur == 129) cur = 192;   // Ё
      prev = thiscur;
    }
    if (!cur) continue;
    if (cur <= 127) ; // skip eng
    else if (cur <= 143) cur -= 80;
    else if (cur <= 191) cur -= 144;
    else cur -= 128;
    qw += (char)pgm_read_byte(&_qwerty_ru[cur]);
  }
  return qw;
}

void setup() {
  Serial.begin(115200);
  Serial.println(ru_to_qw("Привет")); // Ghbdtn
}

void loop() {
}

```

**Comment by kraa965** [comment]
> Вот так можно преобразовать русскую строку в QWERTY
> ```cpp
> const char _qwerty_ru[] PROGMEM = "F<DULT:PBQRKVYJGHCNEA{WXIO}SM\">Zf,dult;pbqrkvyjghcnea[wxio]sm'.z~`";
> 
> String ru_to_qw(const String& ru) {
>   String qw;
>   uint8_t prev = 0;
>   for (int i = 0; i < ru.length(); i++) {
>     uint8_t cur = ru[i];
>     if (cur > 127) {
>       uint8_t thiscur = cur;
>       if (cur > 191) cur = 0;
>       else if (prev == 209 && cur == 145) cur = 193;   // ё
>       else if (prev == 208 && cur == 129) cur = 192;   // Ё
>       prev = thiscur;
>     }
>     if (!cur) continue;
>     
>     if (cur <= 127) {
>       qw += (char)cur;
>       continue;
>     }
>     else if (cur <= 143) cur -= 80;
>     else if (cur <= 191) cur -= 144;
>     else cur -= 128;
>     qw += (char)pgm_read_byte(&_qwerty_ru[cur]);
>   }
>   return qw;
> }
> 
> void setup() {
>   Serial.begin(115200);
>   Serial.println(ru_to_qw("Привет")); // Ghbdtn
> }
> 
> void loop() {
> }
> 
> ```

Спасибо)
Вечером попробую

**Comment by GyverLibs** [comment]
> она у меня не работает

она и не должна работать. Кириллица занимает больше одного байта, писать `'б'` - уже некорректно, буква потеряна. Компилятор должен был об этом предупредить

**Comment by kraa965** [comment]
> Вот так можно преобразовать русскую строку в QWERTY
> ```cpp
> const char _qwerty_ru[] PROGMEM = "F<DULT:PBQRKVYJGHCNEA{WXIO}SM\">Zf,dult;pbqrkvyjghcnea[wxio]sm'.z~`";
> 
> String ru_to_qw(const String& ru) {
>   String qw;
>   uint8_t prev = 0;
>   for (int i = 0; i < ru.length(); i++) {
>     uint8_t cur = ru[i];
>     if (cur > 127) {
>       uint8_t thiscur = cur;
>       if (cur > 191) cur = 0;
>       else if (prev == 209 && cur == 145) cur = 193;   // ё
>       else if (prev == 208 && cur == 129) cur = 192;   // Ё
>       prev = thiscur;
>     }
>     if (!cur) continue;
>     
>     if (cur <= 127) {
>       qw += (char)cur;
>       continue;
>     }
>     else if (cur <= 143) cur -= 80;
>     else if (cur <= 191) cur -= 144;
>     else cur -= 128;
>     qw += (char)pgm_read_byte(&_qwerty_ru[cur]);
>   }
>   return qw;
> }
> 
> void setup() {
>   Serial.begin(115200);
>   Serial.println(ru_to_qw("Привет")); // Ghbdtn
> }
> 
> void loop() {
> }
> 
> ```

Можно этот код под char* адаптировать?

**Comment by GyverLibs** [comment]
Естественно

**Comment by kraa965** [comment]
> Естественно

Подскажите как?

**Comment by GyverLibs** [comment]
Ну например так
```cpp
const char _qwerty_ru[] PROGMEM = "F<DULT:PBQRKVYJGHCNEA{WXIO}SM\">Zf,dult;pbqrkvyjghcnea[wxio]sm'.z~`";

uint16_t ru_to_qw(const char* ru, char* qw) {
  uint16_t len = strlen(ru);
  uint16_t idx = 0;
  uint8_t prev = 0;
  for (int i = 0; i < len; i++) {
    uint8_t cur = ru[i];
    if (cur > 127) {
      uint8_t thiscur = cur;
      if (cur > 191) cur = 0;
      else if (prev == 209 && cur == 145) cur = 193;   // ё
      else if (prev == 208 && cur == 129) cur = 192;   // Ё
      prev = thiscur;
    }
    if (!cur) continue;
    
    if (cur <= 127) {
      qw[idx++] = (char)cur;
      continue;
    }
    else if (cur <= 143) cur -= 80;
    else if (cur <= 191) cur -= 144;
    else cur -= 128;
    qw[idx++] = (char)pgm_read_byte(&_qwerty_ru[cur]);
  }
  qw[idx] = 0;
  return idx;
}

void setup() {
  Serial.begin(115200);

  char* ru = "Привет";
  char qw[strlen(ru)];
  ru_to_qw(ru, qw);

  Serial.println(qw);  // Ghbdtn
}

void loop() {
}
```

**Comment by kraa965** [comment]
> Ну например так
> ```cpp
> const char _qwerty_ru[] PROGMEM = "F<DULT:PBQRKVYJGHCNEA{WXIO}SM\">Zf,dult;pbqrkvyjghcnea[wxio]sm'.z~`";
> 
> uint16_t ru_to_qw(const char* ru, char* qw) {
>   uint16_t len = strlen(ru);
>   uint16_t idx = 0;
>   uint8_t prev = 0;
>   for (int i = 0; i < len; i++) {
>     uint8_t cur = ru[i];
>     if (cur > 127) {
>       uint8_t thiscur = cur;
>       if (cur > 191) cur = 0;
>       else if (prev == 209 && cur == 145) cur = 193;   // ё
>       else if (prev == 208 && cur == 129) cur = 192;   // Ё
>       prev = thiscur;
>     }
>     if (!cur) continue;
>     
>     if (cur <= 127) {
>       qw[idx++] = (char)cur;
>       continue;
>     }
>     else if (cur <= 143) cur -= 80;
>     else if (cur <= 191) cur -= 144;
>     else cur -= 128;
>     qw[idx++] = (char)pgm_read_byte(&_qwerty_ru[cur]);
>   }
>   qw[idx] = 0;
>   return idx;
> }
> 
> void setup() {
>   Serial.begin(115200);
> 
>   char* ru = "Привет";
>   char qw[strlen(ru)];
>   ru_to_qw(ru, qw);
> 
>   Serial.println(qw);  // Ghbdtn
> }
> 
> void loop() {
> }
> ```

Спасибо)
