### ISSUE TITLE
Двухсторонний обмен

### ISSUE THREAD

**Issue by JurySpb** [GyverLibs/EasyHID#23]
Возможно ли на основе  EasyHID сделать двухсторонний обмен с устройством (через USB), аналогично DigiCDC, которая похоже не работает?

**Comment by GyverLibs** [comment]
EasyHID это мышь и клавиатура. Если что то пытаться делать - то на библиотеке VUSB

**Comment by JurySpb** [comment]
Если я не ошибаюсь,  DigiCDC на основе VUSB и что то у них не заладилось... С EasyHID это принципиальная проблема? Клавиатура вроде поддерживает двухсторонний обмен...

**Comment by GyverLibs** [comment]
Почему проблема? EasyHID это удобная обёртка на VUSB для работы с клавиатурой и мышкой

**Comment by JurySpb** [comment]
Т.е. Все равно идти в сторону VUSB ... :)
Спасибо!

**Comment by GyverLibs** [comment]
Да, шо то шо это
