### ISSUE TITLE
Устройство не определено

### ISSUE THREAD

**Issue by shoei1944** [GyverLibs/EasyHID#24]
Windows 10
IDE 1.8.19
EasyHID с GitHUB (последняя)
Arduino Pro Mini 3.3V 16МГц (внешний кварц)

Пробовал разные подключения (минимальные):
С гитхаба (https://github.com/GyverLibs/EasyHID/raw/main/docs/sch1.jpg) - Винда видит устройство, но выдает ошибку дискриптора
С видео - вообще не работает, винда нечего не видит (https://www.youtube.com/watch?v=WSHHDPDFKD0 тайминг 4:15)

Какая нормальная схема актуальная на новую версию прошивки?

**Comment by GyverLibs** [comment]
схемы в репозитории всегда актуальные

**Comment by shoei1944** [comment]
на уно всё заработало, дело в частоте на ардуино про мини
