### ISSUE TITLE
Общение между ПК и ардуино (аналог com порта)

### ISSUE THREAD

**Issue by shoei1944** [GyverLibs/EasyHID#26]
Есть такой проект: https://github.com/rayshobby/hid-serial
Вот еще: http://we.easyelectronics.ru/electro-and-pc/usb-dlya-avr-chast-2-hid-class-na-v-usb.html

Он реализует общение между ардуино и ПК по типу COM порта через HID.
Возможно ли такое реализовать на (с) EasyHID?

**Comment by GyverLibs** [comment]
EasyHID - это удобная ОБЁРТКА на библиотеку VUSB для управления КЛАВИАТУРОЙ и МЫШКОЙ. https://github.com/rayshobby/hid-serial точно также основан на VUSB
