### ISSUE TITLE
Несколько устройств на одной шине

### ISSUE THREAD

**Issue by ilqxa** [GyverLibs/EasyHID#30]
Привет
Подскажите пожалуйста, возможно ли подключить несколько ардуинок на схему, создав на макетной плате общую шину для всех пинов D2 и D4 для их параллельного соединения? Сейчас они между собой конфликтуют и не работают корректно таким образом. Подозреваю, что где-то в конфиге можно указать ID устройства и заставить их отправлять нажатые клавиши обособлено. В файле usbconfig.h такой настройки не увидел

**Comment by Nich1con** [comment]
> Привет Подскажите пожалуйста, возможно ли подключить несколько ардуинок на схему, создав на макетной плате общую шину для всех пинов D2 и D4 для их параллельного соединения? Сейчас они между собой конфликтуют и не работают корректно таким образом. Подозреваю, что где-то в конфиге можно указать ID устройства и заставить их отправлять нажатые клавиши обособлено. В файле usbconfig.h такой настройки не увидел

USB шина работает вообще не так, как вы себе представляете. Передачу инициирует ХОСТ (компутахтер), а не девайс (ардуинка). Так что нельзя размещать несколько девайсов параллельно на шине, USB хабы существуют не просто так, там люди поумнее сидят.

**Comment by ilqxa** [comment]
> > Привет Подскажите пожалуйста, возможно ли подключить несколько ардуинок на схему, создав на макетной плате общую шину для всех пинов D2 и D4 для их параллельного соединения? Сейчас они между собой конфликтуют и не работают корректно таким образом. Подозреваю, что где-то в конфиге можно указать ID устройства и заставить их отправлять нажатые клавиши обособлено. В файле usbconfig.h такой настройки не увидел
> 
> USB шина работает вообще не так, как вы себе представляете. Передачу инициирует ХОСТ (компутахтер), а не девайс (ардуинка). Так что нельзя размещать несколько девайсов параллельно на шине, USB хабы существуют не просто так, там люди поумнее это дело разрабатывали.

Понял, спасибо за скорый ответ. Похоже, мой выбор - собирать сигналы со всех девайсов на одной ардуине, а затем централизовано отправлять их хосту через easyHID

**Comment by Nich1con** [comment]
> > > Привет Подскажите пожалуйста, возможно ли подключить несколько ардуинок на схему, создав на макетной плате общую шину для всех пинов D2 и D4 для их параллельного соединения? Сейчас они между собой конфликтуют и не работают корректно таким образом. Подозреваю, что где-то в конфиге можно указать ID устройства и заставить их отправлять нажатые клавиши обособлено. В файле usbconfig.h такой настройки не увидел
> > 
> > 
> > USB шина работает вообще не так, как вы себе представляете. Передачу инициирует ХОСТ (компутахтер), а не девайс (ардуинка). Так что нельзя размещать несколько девайсов параллельно на шине, USB хабы существуют не просто так, там люди поумнее это дело разрабатывали.
> 
> Понял, спасибо за скорый ответ. Похоже, мой выбор - собирать сигналы со всех девайсов на одной ардуине, а затем централизовано отправлять их хосту через easyHID
Как самый просто вариант - да. Или USB хаб и несколько ардуин, но это неразумно весьма.
