### ISSUE TITLE
Возможность работы с Arduino UNO

### ISSUE THREAD

**Issue by erorstop0x000000000** [GyverLibs/EasyHID#31]
Извините за возможно глупый вопрос. Можно ли использовать данную библиотеку на arduino uno?  При использовании мною данной библиотеки на uno, я столкнулся с тем, что код выполняется, но имитация нажатия на клавиатуру не происходит.
Заранее спасибо)

**Comment by GyverLibs** [comment]
![image](https://github.com/GyverLibs/EasyHID/assets/84599917/90469bdc-ab2e-4e2d-b40d-3b7320ba0aff)
